### ISSUE TITLE
SSL generation certs

### ISSUE THREAD

**Issue by druidking** [atozncoder/netty_secured_chat#1]
Do you have a script on how you generated the certificates for ssl?

**Comment by atozncoder** [comment]
Sorry for a late reply. I just added the files I used to create the certs: 
https://github.com/atozncoder/netty_secured_chat/blob/master/CERTS_SELF_SIGNED_ROOT.md
https://github.com/atozncoder/netty_secured_chat/blob/master/CERTS_INTERMEDIATE.md
https://github.com/atozncoder/netty_secured_chat/blob/master/CERTS_LEAF.md
